spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      leak-detection-threshold: 2000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000        # 10 sec
      max-lifetime: 600000        # 30 sec (VERY IMPORTANT)
      connection-timeout: 30000
      keepalive-time: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
  razorpay:
    key:
      id: ${RAZORPAY_KEY_ID}
      secret: ${RAZORPAY_KEY_SECRET}

app:
  jwt:
    secret: ${JWT_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

cors:
  allowed:
    origins: ${FRONTEND_URL}

marketing:
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    from-number: ${TWILIO_FROM_NUMBER:}
  msg91:
    auth-key: ${MSG91_AUTH_KEY:}
    sender-id: ${MSG91_SENDER_ID:}
  sendgrid:
    api-key: ${SENDGRID_API_KEY:}
